#!/bin/bash

# Usage:
# Open the newest macos clang build job of divvun-suggest, e.g.
# https://travis-ci.org/divvun/divvun-gramcheck/jobs/343314524
# and run on the transfer.sh url from that page, e.g.
# ./get-travis-libs https://transfer.sh/T3T1J/Darwin-64bit-.zip

set -e -u

zip="$(mktemp -t libreoffice-voikko-get-travis-libs.XXXXXXXXXXX)"
cleanup () { rm -f "${zip}"; }
trap cleanup EXIT
wget "$1" -O "${zip}"

unzip -d divvun "${zip}"
