#!/bin/bash

# To run with full debug output, and without opening a window:
# $ PYUNO_LOGLEVEL=ARGS ./kbu-build --headless


### PYTHONPATH doesn't seem to be necessary if the libdivvun files are
### in oxt/pythonpath and mentioned in the SRC_AND_DIST variable in
### Makefile. OTOH, we need the C lib available too, and libdivvun
### installs that, so might as well keep them separate.

if [[ -z $STANDALONE_EXTENSION ]]; then
    export LD_LIBRARY_PATH="$HOME/PREFIX/gtd-gc/lib"
    export PYTHONPATH="$HOME/PREFIX/gtd-gc/lib/python3.6/site-packages"
fi

set -e -u

# cp ~/src/divvun-suggest/python/libdivvun.py oxt/pythonpath/
# cp ~/src/divvun-suggest/python/_libdivvun.cpython-36m-x86_64-linux-gnu.so oxt/pythonpath/

make clean
make
if [[ -z ${STANDALONE_EXTENSION:-} ]]; then
    make oxt
else
    make oxt STANDALONE_EXTENSION=1
fi
( unopkg remove no.divvun.gramcheck || echo meh )
unopkg add -f build/divvun.oxt

### Used by divvun when we want debug output:
export DIVVUN_DEBUG=1

lowriter "$@" sme.odt 2>&1 | awk '
    { color="" }
    $3 ~ /\[CALL,tid/{color="38;2;205;92;92"  }
    $3 ~ /\[CALL,tid/ && $5 ~ /except/ {color="37;1;205;92;91"  }
    $2 == "INFO"     {color="38;2;175;175;135"}
    $2 == "DEBUG"    {color="38;2;100;149;237"}
    $2 == "WARNING"  {color="38;5;161"        }
    color { printf "\033["color"m%s\033[0m\n", $0; next }
          { print }
'
