#!/bin/bash


set -e -u

LIBDIVVUN_MAC_RELEASE=https://github.com/divvun/libdivvun/releases/download/v0.3.0/Darwin-64bit-.zip

if [[ $# -eq 0 ]]; then
    cat <<EOF
This script creates a LibreOffice .oxt file that includes all of
libdivvun and its dependencies as well as whatever language data
(zcheck files) you give it.

The regular .oxt file made by libreoffice-divvun assumes the user has
zcheck language data in e.g. ~/.config/voikko/4 or
/usr/share/voikko/4, while the bundle made by this script includes the
language data in the .oxt file itself.

To run this, please supply the zcheck files to include as arguments,
e.g.

\$ $0 /usr/share/voikko/4/*.zcheck

to make a bundle of all the zcheck divvun language data files in
/usr/share/voikko/4.

If you want to make an .oxt that has no language data, just the code
dependencies, run:

\$ $0 --no-data
EOF
    exit 1
fi

mkdir -p oxt/divvun || true

zip="$(mktemp -t libreoffice-divvun-get-travis-libs.XXXXXXXXXXX)"
cleanup () { rm -f "${zip}"; }
trap cleanup EXIT
if command -V curl 2>/dev/null >/dev/null; then
    curl -L --progress "${LIBDIVVUN_MAC_RELEASE}" > "${zip}"
else
    wget "${LIBDIVVUN_MAC_RELEASE}" -O "${zip}"
fi
unzip -o -d oxt "${zip}"

case "$1" in
    --no-data)
        echo "Not adding any zcheck files to the bundle"
        ;;
    *)
        echo "Adding zcheck files $* to the bundle"
        cp "$@" oxt/divvun
        ;;
esac

export PATH="/Applications/LibreOffice.app/Contents/MacOS/:$PATH"
make oxt STANDALONE_EXTENSION=1

ls build/divvun.oxt
